controller_manager:
  ros__parameters:
    update_rate: 1000
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
joint_trajectory_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - Shoulder_Pitch
      - Shoulder_Yaw
      - Humeral_Rotation
      - Elbow
      - Wrist_Roll
      - Wrist_Pitch
      - Wrist_Yaw
    
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      joint_trajectory_controller:
        joint1:
          trajectory: 0.05
          goal: 0.03