default_acceleration_scaling_factor: 0.1
default_velocity_scaling_factor: 0.1
joint_limits:
  Elbow:
    has_acceleration_limits: true
    has_velocity_limits: true
    max_acceleration: 1.0
    max_velocity: 1.0
  Gripper:
    has_acceleration_limits: true
    has_velocity_limits: true
    max_acceleration: 1.0
    max_velocity: 1.0
  Shoulder_Pitch:
    has_acceleration_limits: true
    has_velocity_limits: true
    max_acceleration: 1.0
    max_velocity: 1.0
  Shoulder_Rotation:
    has_acceleration_limits: true
    has_velocity_limits: true
    max_acceleration: 1.0
    max_velocity: 1.0
  Wrist_Pitch:
    max_effort: 10.0
    max_position: 1.7886215986746576
    max_velocity: 1.0
    min_position: -0.5522330836388308
  Wrist_Roll:
    has_acceleration_limits: true
    has_velocity_limits: true
    max_acceleration: 1.0
    max_velocity: 1.0
